image:
  repository: tccr.io/truecharts/scratch
  tag: latest@sha256:081c282586148e62f1324d86257eaf36226faa209a3975079c68fafaeab59b0a
  pullPolicy: IfNotPresent

controller:
  enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
        port: 9999

updateCRD: false

portal:
  enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

configmap:
  config:
    enabled: true
    data:
      placeholderdata: "something"

ipAddressPools: []
#   - name: example
#     autoAssign: true
#     avoidBuggyIPs: true
#     addresses:
#       - 192.168.1.1-192.168.1.100
L2Advertisements: []
#   - name: l2adv
#     addressPools:
#       - pool1
#     nodeSelectors:
#       - nodeA
BGPAdvertisements: []
#   - name: bgpadv
#     addressPools:
#       - pool1
#     aggregationLength: 24
#     localpref: 100
#     communities:
#       - 1234:1
#     peers:
#       - peer1
Communities: []
#   - name: community1
#     value: 1234:1
Peers: []
#   - name: peer1
#     myASN: 1234
#     password: pass
#     routerID: 1234
#     bfdProfile: profile
#     ebgpMultiHop: false
#     holdTime: 10
#     keepaliveTime: 10
#     peerAddress: 172.30.0.2
#     peerPort: 179
#     sourceAddress: 172.30.0.3
#     nodeSelectors:
#       - nodeA
