env:
  CUSTOM_RES_H: "881"
  CUSTOM_RES_W: "1024"
  DL_URL: https://launchpad.net/rapid/pyqt/0.9.17/+download/install.py
  FORCE_UPDATE: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rapidphotodownloader
  tag: latest@sha256:9381eeb8825abf929cf6ea31882b998a9a67a4f20deaf1c455843ffdc8c02ce0
persistence:
  datadir:
    enabled: true
    mountPath: /rapidphotodownloader
  destinantionfolder:
    enabled: true
    mountPath: /media/destination
  sourcefolder:
    enabled: true
    mountPath: /media/source
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
