image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/debian-bullseye
  tag: latest@sha256:d94dc420a354be7c028b1472e40855f1641e3350e0ac8f702424096d7d82cbb1

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  CUSTOM_RES_H: "1000"
  CUSTOM_RES_W: "1800"
  DATA_PERM: "770"
  DEV: ""
  ROOT_PWD: ""
  USER_LOCALES: en_US.UTF-8 UTF-8

service:
  main:
    ports:
      main:
        port: 8080
        protocol: HTTP
        targetPort: 8080

persistence:
  homedirectory:
    enabled: true
    mountPath: /debian

portal:
  enabled: true
