image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.7.2@sha256:03246dbb8a48899964e1c57eb8a876d3cc31f198d568cf2bf2e46e9389f18fe4

env:
  SABNZBD__HOST_WHITELIST_ENTRIES: ""

service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
