image:
  repository: tccr.io/truecharts/babybuddy
  pullPolicy: IfNotPresent
  tag: 1.13.2@sha256:9371efaea6cb0ce64a36d033652a489c8d4b2c51cf92fbb60a043fb35b9a70f3

env:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_PORT: "5432"
  CSRF_TRUSTED_ORIGINS: ""
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10069
        targetPort: 8000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: babybuddy
  postgresqlDatabase: babybuddy

portal:
  enabled: true
