image:
  repository: tccr.io/truecharts/calibre-web
  pullPolicy: IfNotPresent
  tag: 0.6.19@sha256:98fc172598959ff162002df69f3e4053183cf6e3c207a8244846dde5c08c744f

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8083
        targetPort: 8083

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
