env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/shoko-server
  tag: vdaily@sha256:ed296ad8c59864e88bb6244f1005e0e15512b4a8f58791f5aaf3ab95838fd77e
persistence:
  animefolder:
    enabled: true
    mountPath: /anime
  appdata:
    enabled: true
    mountPath: /home/shoko/.shoko/
  importfolder:
    enabled: true
    mountPath: /import
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8111
        protocol: TCP
        targetPort: 8111

portal:
  enabled: true
