image:
  repository: tccr.io/truecharts/hasty-paste
  pullPolicy: IfNotPresent
  tag: 1.8.0@sha256:3ab77aead86237a92c149edf8c4f802e598aff58e371062242ddbb895264e0cd

hastyPaste:
  new_at_index: false
  enable_public_list: false
  max_body_size: 2000000
  log_level: INFO
  workers: 1
  interface:
    default_use_long_id: false
    default_expire_time_enable: false
    default_expire_time_minutes: 0
    default_expire_time_hours: 1
    default_expire_time_days: 0
  branding:
    title: ""
    description: ""
    icon: ""
    favicon: ""
    css_file: ""
    hide_version: false

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - health-check.sh
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - health-check.sh
  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - health-check.sh

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10601

persistence:
  config:
    enabled: true
    mountPath: /app/data

redis:
  enabled: true
  existingSecret: rediscreds
  redisUsername: default

portal:
  enabled: true
