image:
  repository: tccr.io/truecharts/quassel-web
  pullPolicy: IfNotPresent
  tag: v2021.12.16@sha256:9f5a51c1c1f30fcf5806876dc9a3069def25a3d3aa51e839e5200d2c0c52c811

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  URL_BASE: ""
  QUASSEL_CORE: "0.0.0.0"
  QUASSEL_PORT: 4242

service:
  main:
    ports:
      main:
        targetPort: 64080
        port: 64080

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
