{{/* Make sure all variables are set properly */}}
{{- include "tc.common.loader.init" . }}

{{- include "prometheus.prometheus.prometheus" . }}
{{- include "prometheus.prometheus.additionalprometheusrules" . }}
{{- include "prometheus.prometheus.additionalscrapejobs" . }}
{{- include "prometheus.prometheus.servicemonitor" . }}

{{- include "prometheus.alertmanager.alertmanager" . }}


{{/* Render the templates */}}
{{ include "tc.common.loader.apply" . }}
