image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cura-novnc
  tag: latest@sha256:44700014a98915d230ecaaa42fb50af14e44ce3568fbff9b86353717698f8485
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 16081
        protocol: HTTP
        targetPort: 8080

persistence:
  homefolder:
    enabled: true
    mountPath: /home/cura/
  prints:
    enabled: true
    mountPath: /prints/

portal:
  enabled: true
