image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/amule
  tag: latest@sha256:08ac5dd2895ac3ebbee27dbee5ddff5cdbd1fc36624aff0651976d5eee52b217

env:
  WEBUI_PWD: ""
  WEBUI_TEMPLATE: default

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 4711
        protocol: HTTP
        targetPort: 4711
  porttcp:
    enabled: true
    ports:
      porttcp:
        enabled: true
        port: 4662
        protocol: TCP
        targetPort: 4662
  portudp:
    enabled: true
    ports:
      portudp:
        enabled: true
        port: 4672
        protocol: UDP
        targetPort: 4672

persistence:
  complete:
    enabled: true
    mountPath: /incoming
  config:
    enabled: true
    mountPath: /home/amule/.aMule
  incomplete:
    enabled: true
    mountPath: /temp

portal:
  enabled: true
