image:
  repository: tccr.io/truecharts/bazarr
  pullPolicy: IfNotPresent
  tag: 1.1.4@sha256:90eadb1f4627bbba186749c1e9f5344b0c3fbbf038f0bffe4cd1b813a5cab896

service:
  main:
    ports:
      main:
        port: 6767
        targetPort: 6767

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
