env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/plexripper
  tag: latest@sha256:423b510798fe8bad9b3514b5358cb61cc2a2e0160118db2d1665898eb7c33430
persistence:
  config:
    enabled: true
    mountPath: /config
  downloadfolder:
    enabled: true
    mountPath: /downloads
  moviedestinationfolder:
    enabled: true
    mountPath: /movies
  tv-showdestinationfolder:
    enabled: true
    mountPath: /tvshows
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 7000
        protocol: TCP
        targetPort: 7000

portal:
  enabled: true
