image:
  repository: tccr.io/truecharts/navidrome
  pullPolicy: IfNotPresent
  tag: 0.49.1@sha256:ac5642dbc2dceb1de8e404956f355662d59f74fff96b9df0cf166ff35b42c315

service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533

env:
  ND_SCANINTERVAL: "15m"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_MUSICFOLDER: "/music"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  music:
    enabled: true
    mountPath: "/music"

portal:
  enabled: true
