image:
  repository: tccr.io/truecharts/flatnotes
  tag: 2.1.0@sha256:b9019bbc2ccebb42af170b3b9cb66119033303c80b73f632b58be2d980913ba2
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

secretEnv:
  FLATNOTES_USERNAME: "user"
  FLATNOTES_PASSWORD: "pass"

env:
  FLATNOTES_SECRET_KEY:
    secretKeyRef:
      name: '{{ (include "tc.common.names.fullname" .) }}-secret'
      key: FLATNOTES_SECRET_KEY
  # User Defined
  FLATNOTES_SESSION_EXPIRY_DAYS: 30

service:
  main:
    ports:
      main:
        port: 10350
        protocol: HTTP
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: "/app/data"

portal:
  enabled: true
