image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/zoneminder
  tag: latest@sha256:9289ed31395456baadca5111633987d70d44524ce9ceb0a94f4071b39a802411

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10292
        protocol: HTTPS
        targetPort: 443
  zmninja:
    enabled: true
    ports:
      zmninja:
        enabled: true
        port: 10293
        protocol: TCP
        targetPort: 9000

probes:
  liveness:
    path: "/zm"
  readiness:
    path: "/zm"
  startup:
    path: "/zm"

persistence:
  config:
    enabled: true
    mountPath: /config
  datapath:
    enabled: true
    mountPath: /var/cache/zoneminder

portal:
  enabled: true
