image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/youtransfer
  tag: latest@sha256:7e3253304dce56c3eac8f1966e7a70fdd4e62dcafe4be28cb0152a2d3da3560b

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 5000
        protocol: HTTP
        targetPort: 5000

portal:
  enabled: true

persistence:
  config:
    enabled: true
    mountPath: /opt/youtransfer/config
  uploads:
    enabled: true
    mountPath: /opt/youtransfer/uploads
    type: hostPath
