apiVersion: v2
appVersion: "6.1.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.0.4
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.truecharts.org/
    version: 5.0.9
description: The WordPress rich content management system can utilize plugins, widgets, and themes.
home: https://truecharts.org/docs/charts/incubator/wordpress
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wordpress.png
keywords:
  - wordpress
  - cms
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: wordpress
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/wordpress
  - https://hub.docker.com/_/wordpress
  - https://www.wordpress.org
version: 1.0.0
annotations:
  truecharts.org/catagories: |
    - website
    - CMS
    - Hosting
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
