image:
  repository: tccr.io/truecharts/wordpress
  pullPolicy: IfNotPresent
  tag: 6.1.1@sha256:f6f54523a1dde1484e365c4c7fb636e77f928ea08bfb53b3f199cd615ac53ec4

securityContext:
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsGroup: 0

wordpress:
  user: user
  pass: bitnami
  email: user@example.com
  first_name: TrueCharts
  last_name: TrueCharts
  blog_name: Truecharts Blog
  enable_reverse_proxy_headers: true

smtp:
  enabled: false
  host: ""
  port: ""
  user: ""
  pass: ""

php-config:
  PHP_ENABLE_OPCACHE: "yes"
  PHP_EXPOSE_PHP: ""
  PHP_MAX_EXECUTION_TIME: ""
  PHP_MAX_INPUT_TIME: ""
  PHP_MAX_INPUT_VARS: ""
  PHP_MEMORY_LIMIT: 512M
  PHP_POST_MAX_SIZE: ""
  PHP_UPLOAD_MAX_FILESIZE: ""

envFrom:
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-env-config'
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-env-secret'

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 10591

persistence:
  config:
    enabled: true
    mountPath: /bitnami/wordpress

mariadb:
  enabled: true
  mariadbUsername: wordpress
  mariadbDatabase: wordpress
  existingSecret: mariadbcreds

portal:
  enabled: true
