image:
  repository: tccr.io/truecharts/webnut
  pullPolicy: IfNotPresent
  tag: latest@sha256:5fb697a7699c1d4013760d05df790cfb3a8484ad1cb0c4a6d3b692b3bae41466

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  UPS_USER: monuser
  UPS_PASSWORD: secret

env:
  UPS_HOST: "127.0.0.1"
  UPS_PORT: 3493

service:
  main:
    ports:
      main:
        port: 10585
        protocol: HTTP
        targetPort: 6543

portal:
  enabled: true
