env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chronograf
  tag: latest@sha256:2ffaf21a11a060bdace6973aae77cc5e0e94ff3609ab306e2c77affcc68dd076
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8888
        protocol: TCP
        targetPort: 8888

portal:
  enabled: true
