image:
  repository: tccr.io/truecharts/pylon
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:5f55bbbb3c9093a9300de80685f579c2c3fcdeb5291214c3fe073db0ebb0c84a

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  PYUSER: ""
  PYPASS: ""

env:
  GITURL: ""

service:
  main:
    ports:
      main:
        targetPort: 3131
        port: 3131

persistence:
  code:
    enabled: true
    mountPath: "/code"
  varrun:
    enabled: true

portal:
  enabled: true
