image:
  repository: tccr.io/truecharts/kitchenowl-web
  pullPolicy: IfNotPresent
  tag: latest@sha256:b9840abb3ce33249d783a94f7a45d79e5f1f833ec6cdd64136806b58384957c3

backendImage:
  repository: tccr.io/truecharts/kitchenowl-backend
  pullPolicy: IfNotPresent
  tag: latest@sha256:b1efa6d8d216e572fe728352dc8c8cf7d8decb41e64b04a7967eee0d3de2e393

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  FRONT_URL: "http://localhost:10246"
  # Backend listens on 5000 websockets.
  BACK_URL: "localhost:5000"

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 80
        port: 10246

additionalContainers:
  backend:
    name: backend
    image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
    env:
      - name: FRONT_URL
        value: "{{ .Values.env.FRONT_URL }}"
        # Backend also listens on 80, but afaik there is no use as of now
        # Changed port to 81 to avoid conflict with frontend
      - name: HTTP_PORT
        value: "81"
      - name: JWT_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: kitchenowl-secrets
            key: JWT_SECRET_KEY
    volumeMounts:
      - name: data
        mountPath: "/data"

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
