image:
  repository: tccr.io/truecharts/emulatorjs
  pullPolicy: IfNotPresent
  tag: v1.7.2@sha256:1149966e6bdacb209b6c4a6be8a4b341320c95d7b02c1603c0f21a16d91f33ec

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10130
  front:
    enabled: true
    ports:
      front:
        enabled: true
        targetPort: 80
        port: 10124
  ipfs:
    enabled: true
    ports:
      ipfs:
        enabled: true
        targetPort: 4001
        port: 10138

ingress:
  front:
    autoLink: true

persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true

portal:
  enabled: true
