image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/crafty-4
  tag: 4.0.20@sha256:08664178b0c8f70d6ba4a2cc726b3dc84ce5de07de3925b176015efa7cb026ad

podSecurityContext:
  runAsGroup: 1000
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: false

probes:
  liveness:
    type: HTTPS
    path: /
  readiness:
    type: HTTPS
    path: /
  startup:
    type: HTTPS
    path: /

service:
  main:
    ports:
      main:
        port: 10586
        protocol: HTTPS
        targetPort: 8443
  redirects:
    enabled: true
    ports:
      redirects:
        enabled: true
        port: 10587
        protocol: HTTPS
        targetPort: 8000
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25565
        targetPort: 25565
  bedrock:
    enabled: true
    ports:
      bedrock:
        enabled: true
        port: 19132
        protocol: UDP
        targetPort: 19132

persistence:
  config:
    enabled: true
    mountPath: /crafty/app/config
  servers:
    enabled: true
    mountPath: /crafty/servers
  logs:
    enabled: true
    mountPath: /crafty/logs
  import:
    enabled: true
    mountPath: /crafty/import
  backups:
    enabled: true
    mountPath: /crafty/backups

portal:
  enabled: true
