image:
  repository: tccr.io/truecharts/ngircd
  pullPolicy: IfNotPresent
  tag: v2021.11.21@sha256:205a56ca8fc82b25b42c84bad0cb088e0b56804d181ab0e5c32f339df7502806

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 6667
        port: 6667

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
