image:
  repository: tccr.io/truecharts/miniflux
  tag: 2.0.42@sha256:61ea481fd81efcc9f12e355643eeafc1bc56ceebd5036b55423d5e4371395db9
  pullPolicy: IfNotPresent

secretEnv:
  # -- Admin user login, it's used only if `CREATE_ADMIN` is enabled.
  ADMIN_USERNAME: "admin"
  # -- Admin user password, it's used only if `CREATE_ADMIN` is enabled.
  ADMIN_PASSWORD: "changeme"
env:
  RUN_MIGRATIONS: 1
  CREATE_ADMIN: 1
  DATABASE_URL:
    secretKeyRef:
      name: dbcreds
      key: urlnossl

service:
  main:
    ports:
      main:
        port: 10091
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      httpGet:
        path: /healthcheck
        port: 8080

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlDatabase: miniflux
  postgresqlUsername: miniflux

portal:
  enabled: true
