image:
  repository: tccr.io/truecharts/scrutiny
  pullPolicy: IfNotPresent
  tag: 0.6.0@sha256:db378aa16404d19afecfe0e38330799b2aeb3c5d0cc670b9d40881ad1d13c4ab

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  privileged: true
  allowPrivilegeEscalation: true
  capabilities:
    # RawIO is for HDDs
    # SYS_ADMIN is for NVMEs
    add:
      - SYS_RAWIO
      - SYS_ADMIN

env:
  COLLECTOR_CRON_SCHEDULE: "0 0 * * *"
  COLLECTOR_HOST_ID: "TrueNAS"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

probes:
  liveness:
    path: "/api/health"
  readiness:
    path: "/api/health"
  startup:
    path: "/api/health"

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10151

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/opt/scrutiny/config"
  influxdb:
    enabled: true
    mountPath: "/opt/scrutiny/influxdb"
  udev:
    enabled: true
    type: hostPath
    hostPath: "/run/udev"
    mountPath: "/run/udev"
    readOnly: true

portal:
  enabled: true
