image:
  repository: tccr.io/truecharts/couchpotato
  pullPolicy: IfNotPresent
  tag: v2021.11.22@sha256:8ae544711733eb7b9cffc7c98d08e5ae863615b4c2ce01921130e53cc0c3126a

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5050
        port: 10139

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
