image:
  repository: tccr.io/truecharts/soft-serve
  pullPolicy: IfNotPresent
  tag: 0.4.4@sha256:758d04854964a10967c0895e3abca055ad569c8630664e3efe5907003c1647fc

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

softserve:
  host: localhost
  key_path: /.ssh/soft_serve_server_ed25519
  init_admin_key: ""

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-env-secret'

service:
  main:
    ports:
      main:
        protocol: TCP
        port: 23231

persistence:
  config:
    enabled: true
    mountPath: /soft-serve
  ssh:
    enabled: true
    mountPath: /.ssh
  repos:
    enabled: true
    mountPath: /repos

portal:
  enabled: false
