image:
  repository: tccr.io/truecharts/heimdall
  tag: 2.5.5@sha256:1e69a80a4ac050fd7d3679aeff1489534de03d7a023cd5080156137b7a213126
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

probes:
  startup:
    enabled: true

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
