# Fake external service image
image:
  repository: tccr.io/truecharts/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:b59737dd7105f1711d838556f4e59d833e6cae19460fd46ac0327c802f1349d7

# Disable Deployment
controller:
  enabled: false

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    ports:
      main:
        Type: HTTPS
        port: 10003
        targetPort: 443

portal:
  enabled: true
