image:
  repository: tccr.io/truecharts/docusaurus
  pullPolicy: IfNotPresent
  tag: latest@sha256:00ca680f4ebfcb01f8f082c70a737db29963b3b2323b71eb701b0a4eef0170c9

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 80
        port: 13080

env:
  TARGET_UID: "{{ .Values.security.PUID }}"
  TARGET_GID: "{{ .Values.podSecurityContext.fsGroup }}"
  AUTO_UPDATE: true
  WEBSITE_NAME: "Docusaurus HomeLab Website"
  TEMPLATE: classic

persistence:
  config:
    enabled: true
    mountPath: "/docusaurus"

portal:
  enabled: true
