image:
  repository: tccr.io/truecharts/airdcpp-webclient
  pullPolicy: IfNotPresent
  tag: 2.11.3@sha256:517455edfda62b11eb6f6246e87244ef104bbdf6b51c83c2e470c917b54400c8

service:
  main:
    ports:
      main:
        port: 10155
        targetPort: 5600
  unencrypted-tcp:
    enabled: true
    ports:
      unencrypted-tcp:
        enabled: true
        port: 21248
        targetPort: 21248
  encrypted-tcp:
    enabled: true
    ports:
      encrypted-tcp:
        enabled: true
        port: 21249
        targetPort: 21249
  search-udp:
    enabled: true
    ports:
      search-udp:
        enabled: true
        protocol: UDP
        port: 21248
        targetPort: 21248

persistence:
  config:
    enabled: true
    mountPath: "/.airdcpp"

portal:
  enabled: true
