env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/grafana-image-renderer
  tag: latest@sha256:e5b2ccf2d245b7487056d5b886841aec0959552e447a69123b857835f4363c20
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
