image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/prusaslicer-novnc
  tag: latest@sha256:71977d64c531e36ec0196e8899f2c098dca55edb3d7e2698a207db295066b8bf
persistence:
  configsfolder:
    enabled: true
    mountPath: /configs/
  prints:
    enabled: true
    mountPath: /prints/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 16080
        protocol: HTTP
        targetPort: 8080

portal:
  enabled: true

env:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
