env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tasmocompiler
  tag: latest@sha256:bbfd98ee35a222ceb38af152ad3e1f1935c5174dc41cc027fd89d0182e6b3339
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
