image:
  repository: tccr.io/truecharts/shiori
  pullPolicy: IfNotPresent
  tag: 1.5.3@sha256:99696bfc727ab1792297cba1e0ba755953bc0cfa38f2c19532c56d68985479a8

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-secret'

service:
  main:
    ports:
      main:
        port: 10098
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: /data
  varrun:
    enabled: true

postgresql:
  enabled: true
  existingSecret: dbcreds
  postgresqlUsername: shiori
  postgresqlDatabase: shiori

portal:
  enabled: true
