image:
  repository: tccr.io/truecharts/deluge
  pullPolicy: IfNotPresent
  tag: 2.1.1@sha256:d3c7b1026d8a20dcfb71dab5bc77b8a799fdf166fe28914ddf61993afb0a6204

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8112
        targetPort: 8112
  torrent:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 51413
        targetPort: 51413
  torrent-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 51413
        targetPort: 51413
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
