image:
  repository: tccr.io/truecharts/nntp2nntp
  pullPolicy: IfNotPresent
  tag: 0.3.20221013@sha256:c5e1743c1d921a23ee96858d8eed4e9b05d55c85c7d4149d6f1e69e3fa3c77c3

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 1563
        port: 1563

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
