image:
  repository: tccr.io/truecharts/retrobot
  pullPolicy: IfNotPresent
  tag: latest@sha256:7e8a7816010b6240d9da7d2c9555738159ff0bf2f672e8d505a3d3102b4c5853

secretEnv:
  DISCORD_TOKEN: ""

env:
  MAX_WORKERS: -1
  MAX_WORKERS_PER_GAME: 3
  RECORDING_FRAMERATE: 30

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  data:
    enabled: true
    mountPath: /retrobot/data

portal:
  enabled: false
