image:
  repository: tccr.io/truecharts/icinga2
  tag: 2.13.6@sha256:4ab5db64ef09a6095b07530273a3403958d51e3f990c0ea092e288211e963ae9
  pullPolicy: IfNotPresent

env:
  DEFAULT_MYSQL_USER: icinga2
  DEFAULT_MYSQL_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  DEFAULT_MYSQL_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  MYSQL_ROOT_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-root-password

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10114
        targetPort: 80
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 10115
        targetPort: 443
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 10116
        targetPort: 5665

persistence:
  config:
    enabled: true
    mountPath: "/etc/icinga2"
  data:
    enabled: true
    mountPath: "/var/lib/icinga2"
  web:
    enabled: true
    mountPath: "/etc/icingaweb2"
  ssmtp:
    enabled: true
    mountPath: "/etc/ssmtp"

mariadb:
  enabled: true
  mariadbUsername: icinga2
  mariadbDatabase: icinga2
  existingSecret: "mariadbcreds"

portal:
  enabled: true
