image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/kasm
  tag: 1.12.0@sha256:18c929908d80199b2240b0a1787f93393272220750b4003978c8a7513b08cb0d

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
  fsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  allowPrivilegeEscalation: true
  privileged: true

secretEnv:
  DOCKER_HUB_PASSWORD: ""
  DOCKER_HUB_USERNAME: ""

env:
  KASM_PORT: "{{ .Values.service.main.ports.main.port }}"

kasm:
  mountUdev: false
  mountInput: false

probes:
  liveness:
    type: HTTPS
    path: /
    port: "{{ .Values.service.admin.ports.admin.targetPort }}"
  readiness:
    type: HTTPS
    path: /
    port: "{{ .Values.service.admin.ports.admin.targetPort }}"
  startup:
    type: HTTPS
    path: /
    port: "{{ .Values.service.admin.ports.admin.targetPort }}"

service:
  main:
    ports:
      main:
        port: 10350
        protocol: HTTPS
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        port: 10351
        protocol: HTTPS
        targetPort: 3000

persistence:
  data:
    enabled: true
    mountPath: /opt
  varrun:
    enabled: true

portal:
  enabled: true
