env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1280"
  NOVNC_RESIZE: remote
  RUNASROOT: "false"
  USER_LOCALES: en_US.UTF-8 UTF-8
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/krusader
  tag: latest@sha256:05c4f33ac1576a3aee97a7b06af23f370455af3f61b584c32c62932d2305a6ed
persistence:
  containerpath:
    enabled: true
    mountPath: /krusader
  datapath:
    enabled: true
    mountPath: /mnt/user
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
