env:
  CUSTOM_RES_H: "600"
  CUSTOM_RES_W: "800"
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/megasync
  tag: latest@sha256:aef378b3fdef2a94b1f5042354b02d9d7f06d70c2dae728f903ddccb3c163255
persistence:
  datadir:
    enabled: true
    mountPath: /megasync/.local/share/data/Mega Limited/MEGAsync
  hostpath:
    enabled: true
    mountPath: /mnt/host
    readOnly: true
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
