image:
  repository: tccr.io/truecharts/timetagger
  tag: 23.1.1@sha256:b1260e02c2dc2f783fb813642da23ece60577729e80c341e00ad90a20599b6ec
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  tg_user: "admin"
  tg_pass: "changeme"
  TIMETAGGER_CREDENTIALS: "{{ htpasswd .Values.secretEnv.tg_user .Values.secretEnv.tg_pass }}"

env:
  TIMETAGGER_BIND: "0.0.0.0:{{ .Values.service.main.ports.main.port }}"
  TIMETAGGER_LOG_LEVEL: "info"

service:
  main:
    ports:
      main:
        port: 10286

persistence:
  config:
    enabled: true
    mountPath: "/root/_timetagger"

portal:
  enabled: true
