image:
  repository: tccr.io/truecharts/esphome
  pullPolicy: IfNotPresent
  tag: 2022.12.8@sha256:3832c317a498dfa0f84d4a2d36cafb52fdf7d22a57e0dfaf148bf718c96faa2a

# App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  privileged: true
  allowPrivilegeEscalation: true

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 6052
        targetPort: 6052

env:
  ESPHOME_DASHBOARD_USE_PING: false
  ESPHOME_DASHBOARD_RELATIVE_URL: /
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HASSIO:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:

persistence:
  config:
    enabled: true
    mountPath: /config
  platformio:
    enabled: true
    mountPath: /.platformio

portal:
  enabled: true
