image:
  repository: tccr.io/truecharts/octoprint
  tag: 1.8.6@sha256:74865bb376361a7df850109021715e63d3c04c64257db7d1772a53d413e0d28e
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  ENABLE_MJPG_STREAMER: "true"
  # -- sets the Mjpg stream imput parameters
  # Example "-y -n -r 640x480"
  MJPG_STREAMER_INPUT:
  # -- sets the camera dev parameters
  # Example "/dev/video0"
  CAMERA_DEV:

service:
  main:
    ports:
      main:
        port: 10021
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: "/octoprint"
  varrun:
    enabled: true

portal:
  enabled: true
