image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/recyclarr
  tag: 4.2.0@sha256:769cc3df9b064be0bc2ed75d6aa1ee50f516e3970f76a303eb4fecf0cb4735ae

podSecurityContext:
  runAsGroup: 568
  runAsUser: 568

env:
  CRON_SCHEDULE: "@daily"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

installContainers:
  initconfig:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    volumeMounts:
      - name: config
        mountPath: "/config"
    command: ["recyclarr", "create-config"]

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: false
