env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cloudbeaver
  tag: latest@sha256:2a47d0d78051b52191fce998d60ffacca9c02a83bce07d9d772328bb2efb653e
persistence:
  appdata:
    enabled: true
    mountPath: /opt/cloudbeaver/workspace
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8978
        protocol: TCP
        targetPort: 8978

portal:
  enabled: true
