image:
  repository: tccr.io/truecharts/unpackerr
  pullPolicy: IfNotPresent
  tag: 0.11.1@sha256:2e657dcea297a98bb40d264b0c9cebce54c899ce7665e686e0eca19fb24fe5f4

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  downloads:
    enabled: true
    mountPath: "/downloads"
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    #
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

portal:
  enabled: false
