env:
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/prusaslicer-novnc
  tag: latest@sha256:f72a34df05da0e7130531a9ef81bac19e6f7bbf1dbcec982bb931d7e0b86fadc
persistence:
  configsfolder:
    enabled: true
    mountPath: /configs/
  prints:
    enabled: true
    mountPath: /prints/
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
