image:
  repository: tccr.io/truecharts/grocy
  tag: 3.3.2@sha256:420b27dbb45784cd1deebb4d195aa4c559ae83540b3312ba1b492e97dfd91304
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
