image:
  repository: tccr.io/truecharts/stash
  tag: 0.18.0@sha256:46e25f05c2ddb922dff19eaacc8e872778c81b1f56c85de4dc77d8571666924b
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  STASH_PORT: "{{ .Values.service.main.ports.main.port }}"
  # STASH_STASH:
  # STASH_GENERATED:
  # STASH_METADATA:
  # STASH_CACHE:

service:
  main:
    ports:
      main:
        port: 9999

persistence:
  config:
    enabled: true
    mountPath: "/root/.stash"

portal:
  enabled: true
