image:
  repository: tccr.io/truecharts/navidrome
  pullPolicy: IfNotPresent
  tag: 0.48.0@sha256:a133b55a3a0b5840f3412a96a34a099cc2f24b5d42418eca84a0ad72d5c8fa40

service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533

env:
  ND_SCANINTERVAL: "15m"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_MUSICFOLDER: "/music"

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
