image:
  repository: tccr.io/truecharts/duckdns
  pullPolicy: IfNotPresent
  tag: latest@sha256:0915870cc8056ef619195a81969894b22f75bfdd07fce04253df888c3decf5e7

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  TOKEN: ""

env:
  SUBDOMAINS: ""
  LOG_FILE: false

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: false
