apiVersion: v2
appVersion: "0.2.3"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.0.4
deprecated: false
description: Traggo is a tag-based time tracking tool. In Traggo there are no tasks, only tagged time spans.
home: https://truecharts.org/docs/charts/incubator/traggo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/traggo.png
keywords:
  - time-tracking
  - tag
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: traggo
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/traggo
  - https://github.com/traggo/server
type: application
version: 0.0.2
annotations:
  truecharts.org/catagories: |
    - productivity
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
