image:
  repository: tccr.io/truecharts/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 3.9.1@sha256:d7f9dc1e6c0364f762d89bcb36d9265f2b59e06e6ba5a266e8d629339ef2d226

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  SHLINK_SERVER_URL: ""
  SHLINK_SERVER_API_KEY: ""
  SHLINK_SERVER_NAME: ""

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 10154
        protocol: HTTP

portal:
  enabled: true
