image:
  repository: tccr.io/truecharts/ubooquity
  pullPolicy: IfNotPresent
  tag: v2.1.2@sha256:604e6e4682b0f3bd60017b4fed537409123f14eef21f5373a29a4a3e16c6ec30

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  MAXMEM: 512

service:
  main:
    ports:
      main:
        targetPort: 2202
        port: 2202
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        targetPort: 2203
        port: 2203

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  books:
    enabled: true
    mountPath: "/books"
  comics:
    enabled: true
    mountPath: "/comics"
  files:
    enabled: true
    mountPath: "/files"

portal:
  enabled: true
