image:
  repository: tccr.io/truecharts/heimdall
  tag: 2.5.5@sha256:8456359363e59d24570db3e44e94e33ae0336e919c5ecd1cac937caf7722bc84
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

probes:
  startup:
    enabled: true

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
