env:
  DL_URL: http://installer.altitudegame.com/0.0.1/altitude.sh
  GAME_PARAMS: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/altitude
  tag: latest@sha256:3f823323a22133ac62507cf0b69975b50dc471688d5f84ffbf81f1aa6c17874e
persistence:
  serverfiles:
    enabled: true
    mountPath: /altitude
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 27276
        protocol: UDP
        targetPort: 27276

portal:
  enabled: true
