image:
  repository: tccr.io/truecharts/embystat
  pullPolicy: IfNotPresent
  tag: v0.2.0@sha256:872073ee3176d63c4442091bccb7dcaa8ff42d9ebf0b1ad44e3b68607775f32c

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 6555
        port: 6555

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
