image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/crafty-4
  tag: 4.0.16@sha256:6325ffbb4ee84693dc571f714a43ca0620e70d7f718771360599bd0bfc99b650

podSecurityContext:
  runAsGroup: 1000
  runAsUser: 1000

securityContext:
  readOnlyRootFilesystem: false

probes:
  liveness:
    type: HTTPS
    path: /
  readiness:
    type: HTTPS
    path: /
  startup:
    type: HTTPS
    path: /

service:
  main:
    ports:
      main:
        port: 10586
        protocol: HTTPS
        targetPort: 8443
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 10587
        protocol: HTTPS
        targetPort: 8000
  bedrock:
    enabled: true
    ports:
      bedrock:
        enabled: true
        port: 19132
        protocol: UDP
        targetPort: 19132
  dynmap:
    enabled: true
    ports:
      dynmap:
        enabled: true
        port: 8124
        targetPort: 8123
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25500
        targetPort: 25500

persistence:
  config:
    enabled: true
    mountPath: /crafty/app/config
  serverfiles:
    enabled: true
    mountPath: /crafty/servers
  serverlogs:
    enabled: true
    mountPath: /crafty/logs
  import:
    enabled: true
    mountPath: /crafty/import
  backup:
    enabled: true
    mountPath: /crafty/backups

portal:
  enabled: true
