image:
  repository: tccr.io/truecharts/photoprism
  tag: v221118@sha256:eed14e57bf198d5263bbd5e6631a77f78a3bb812556cfc1d3267e107e5b23baa
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

secretEnv:
  PHOTOPRISM_ADMIN_PASSWORD: "please-change"

env:
  HOME: "/photoprism"
  PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
  PHOTOPRISM_IMPORT_PATH: "/photoprism/import"
  PHOTOPRISM_TEMP_PATH: "/photoprism_temp"
  PHOTOPRISM_STORAGE_PATH: "/assets/storage"
  PHOTOPRISM_SIDECAR_PATH: "/assets/sidecar"
  PHOTOPRISM_CACHE_PATH: "/assets/cache"
  PHOTOPRISM_CONFIG_PATH: "/assets/config"
  PROTOPRISM_BACKUP_PATH: "/assets/backup"
  PHOTOPRISM_PUBLIC: false
  PHOTOPRISM_UID: "{{ .Values.podSecurityContext.runAsUser }}"
  PHOTOPRISM_GID: "{{ .Values.podSecurityContext.runAsGroup }}"
  PHOTOPRISM_UMASK: "{{ .Values.env.UMASK }}"
  PHOTOPRISM_DATABASE_DRIVER: "mysql"
  PHOTOPRISM_DATABASE_NAME: "photoprism"
  PHOTOPRISM_DATABASE_USER: "photoprism"
  PHOTOPRISM_DATABASE_SERVER:
    secretKeyRef:
      name: mariadbcreds
      key: plainporthost
  PHOTOPRISM_DATABASE_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

service:
  main:
    ports:
      main:
        port: 2342
        targetPort: 2342

persistence:
  storage:
    enabled: true
    mountPath: "/assets"
  photoprismtemp:
    enabled: true
    mountPath: "/photoprism_temp"
    type: emptyDir

mariadb:
  enabled: true
  mariadbUsername: photoprism
  mariadbDatabase: photoprism
  existingSecret: "mariadbcreds"

portal:
  enabled: true
