image:
  repository: tccr.io/truecharts/lanraragi
  tag: 0.8.81@sha256:47f25921d7a158c848dc9d89daea08378894bd4ffe9f204337e633c87ccf5d25
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  LRR_UID: "{{ .Values.security.PUID }}"
  LRR_GID: "{{ .Values.podSecurityContext.fsGroup }}"

service:
  main:
    ports:
      main:
        port: 10177
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/database"
  content:
    enabled: true
    mountPath: "/home/koyomi/lanraragi/content"

portal:
  enabled: true
