image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/stationeers
  tag: latest@sha256:00dcfb407c0dc9901e65481d437e3eb6b6dc78e9d57617ab2ab251b951db88f3

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  USERNAME: ""
  PASSWRD: ""

env:
  GAME_ID: "600760"
  GAME_PARAMS: AutoSave true SaveInterval 300
  VALIDATE: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 27015
        protocol: UDP
        targetPort: 27015
  gameport:
    enabled: true
    ports:
      gameport:
        enabled: true
        port: 27500
        protocol: UDP
        targetPort: 27500

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

portal:
  enabled: true
