image:
  repository: tccr.io/truecharts/znc
  pullPolicy: IfNotPresent
  tag: v1.8.2@sha256:ca99c244a4fb2a52e26bc3394f7e1fefa4311ec9c17b76a3dcd9c6dcc05697a9

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
