env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/statping-ng
  tag: latest@sha256:9b11d641840d9067e5815fa0ea2ed52b3bacca0101db026d62f79cc4771fa04c
persistence:
  config:
    enabled: true
    mountPath: /app
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8366
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
