image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/duplicacy
  tag: latest@sha256:aa4053828a9d7b916397035290ff9f46bf3dedebfa7e65d8469888471adc3744

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 3875
        protocol: HTTP
        targetPort: 3875

persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs

portal:
  enabled: true
