env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/wordle
  tag: latest@sha256:be97f3f1db680081bbbb47dc512716ba30c8dce4967274a5031685e1b2094677
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
