image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/universal-media-server
  tag: latest@sha256:57d8aa00198671c751e04ffec72ef9fc0f1d8692ee33685a3e247a0266fdd8be

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 9001
        protocol: HTTP
        targetPort: 9001
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 1044
        protocol: TCP
        targetPort: 1044
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 5001
        protocol: TCP
        targetPort: 5001

persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media

portal:
  enabled: true
