env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/archiveteam-warrior
  tag: latest@sha256:726cf4ab61be6525626c67aba0f0aa86e5194bc6f96e54a22b74567489fbd484

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8001
        protocol: TCP
        targetPort: 8001

portal:
  enabled: true
