image:
  repository: tccr.io/truecharts/papermerge
  pullPolicy: IfNotPresent
  tag: v2.0.1@sha256:a19f99854b4c945166150b1a29badcb390fadcc9ac6a4f95b90ea37697772dca

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  REDIS_URL:
    secretKeyRef:
      name: rediscreds
      key: url

service:
  main:
    ports:
      main:
        targetPort: 8000
        port: 10141

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: papermerge

portal:
  enabled: true
