image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.7.1@sha256:ef28fdb2c4d8e44ab2964fde8821dabed6c90d2f2b41bab25a28cbfb01ca6261

env:
  SABNZBD__HOST_WHITELIST_ENTRIES: ""

service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
