env:
  CUSTOM_RES_H: "768"
  CUSTOM_RES_W: "1024"
  DATA_PERM: "770"
  UMASK: "000"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/electrum
  tag: latest@sha256:b0b6afaf9513222d6e78bddf5a31f4575ec01ae727eb1c1b76cbd3f7a33667fb
persistence:
  datapath:
    enabled: true
    mountPath: /electrum
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
