env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/yacreaderlibraryserver
  tag: latest@sha256:aaa41894580e03dc23875754e7646a32beaf77ab42666d3b4c5fa894cfc53df2
persistence:
  comics:
    enabled: true
    mountPath: /comics
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
