apiVersion: v2
appVersion: "0.90.80"
description: Status page for monitoring your websites and applications
name: statping-ng
version: 11.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - statping
  - status
  - status-page
home: https://truecharts.org/charts/stable/statping-ng
icon: https://truecharts.org/img/hotlink-ok/chart-icons/statping-ng.png
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/statping-ng
  - https://github.com/statping/statping
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.21
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
