image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/funkwhale
  tag: 1.2.9@sha256:fa04e7bbd2d1c8d0a46aedffaf9f53ba52ed771676d40db8a639db6e2c4f4c57

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  DJANGO_SECRET_KEY:
    secretKeyRef:
      name: '{{ printf "%s-secret" (include "tc.common.names.fullname" .) }}'
      key: DJANGO_SECRET_KEY
  FUNKWHALE_HOSTNAME: yourdomain.funkwhale
  NESTED_PROXY: "0"

service:
  main:
    ports:
      main:
        port: 10236
        protocol: HTTP
        targetPort: 5000

persistence:
  data:
    enabled: true
    mountPath: /data
  musicpath:
    enabled: true
    mountPath: /music
    readOnly: true

portal:
  enabled: true
