apiVersion: v2
appVersion: "2022.12.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 11.0.18
  - condition: redis.enabled
    name: redis
    repository: https://charts.truecharts.org
    version: 5.0.24
description: authentik is an open-source Identity Provider focused on flexibility and versatility.
home: https://truecharts.org/charts/stable/authentik
icon: https://truecharts.org/img/hotlink-ok/chart-icons/authentik.png
keywords:
  - authentik
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: authentik
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/authentik
  - https://github.com/goauthentik/authentik
  - https://goauthentik.io/docs/
version: 10.0.31
annotations:
  truecharts.org/catagories: |
    - authentication
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
