image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.11.1@sha256:5f3e7b99488caaa613a3e18560d978e5be34df39f4909cab68afea6fcc544b72

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
