image:
  repository: tccr.io/truecharts/fleet
  pullPolicy: IfNotPresent
  tag: 2.3.3@sha256:2bc17684fed67948551469744e4c4ce00d3aa3f0dc59653662bb4ccf77f4c8a3

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  # fleet_admin_secret: ""  (Optional)

env:
  fleet_admin_authentication_type: DATABASE
  fleet_database_username: fleet
  fleet_database_url:
    secretKeyRef:
      name: mariadbcreds
      key: jdbc-mariadb
  fleet_database_password:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10145

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

mariadb:
  enabled: true
  mariadbUsername: fleet
  mariadbDatabase: fleet
  existingSecret: "mariadbcreds"

portal:
  enabled: true
