image:
  repository: tccr.io/truecharts/code-server
  pullPolicy: IfNotPresent
  tag: 4.9.1@sha256:b339bd8f6da4c73c0259d6951991278aa1595a6be570a207ce635c75aac9893d

args:
  - --user-data-dir
  - "/config/.vscode"
  - --auth
  - none

env:
  PROXY_DOMAIN: ""

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10063
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
