apiVersion: v2
appVersion: "cpu"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: false
description: Open-source inpainting tool powered by SOTA AI model.
home: https://truecharts.org/charts/incubator/lama-cleaner
icon: https://truecharts.org/img/hotlink-ok/chart-icons/lama-cleaner.png
keywords:
  - lama-cleaner
  - media
  - AI
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: lama-cleaner
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/lama-cleaner
  - https://github.com/Sanster/lama-cleaner
type: application
version: 0.0.5
annotations:
  truecharts.org/catagories: |
    - media
    - AI
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
