image:
  repository: tccr.io/truecharts/noisedash
  tag: 0.6.8@sha256:ee04d57c6c7a48ba204e2096addbbbf1f7312490d5a251f431bc6cd98804c059
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

noisedash:
  max_sample_size_in_bytes: 10737418240

service:
  main:
    ports:
      main:
        port: 10328

persistence:
  db:
    enabled: true
    mountPath: /var/noisedash/db
  samples:
    enabled: true
    mountPath: /var/noisedash/samples

portal:
  enabled: true
