image:
  repository: tccr.io/truecharts/website-shot
  tag: latest@sha256:0c0721540f4917fac07b170bf30769305dcf9b1f11cef8e4940812996e344f67
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 10221
        targetPort: 3000

persistence:
  screenshots:
    enabled: true
    mountPath: "/usr/src/website-shot/screenshots"

portal:
  enabled: true
