image:
  repository: tccr.io/truecharts/zwavejs-ui
  pullPolicy: IfNotPresent
  tag: 8.8.3@sha256:9bb6c195743188303668bc5059f9e1399ad76cd331dc6ff997eac4ea5ad51e5e

securityContext:
  readOnlyRootFilesystem: false

# env: {}
#   OZW_NETWORK_KEY:

probes:
  liveness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  readiness:
    enabled: true
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10
  startup:
    enabled: false
    # custom: true
    # spec:
    #   failureThreshold: 5
    #   httpGet:
    #     path: /health
    #     port: http
    #     httpHeaders:
    #       - name: Accept
    #         value: text/plain
    #   initialDelaySeconds: 30
    #   periodSeconds: 10
    #   timeoutSeconds: 10

service:
  main:
    ports:
      main:
        port: 8091
        targetPort: 8091
  ws:
    enabled: true
    ports:
      ws:
        enabled: true
        port: 10046
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/usr/src/app/store"
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zwave-controller

portal:
  enabled: true
