image:
  repository: tccr.io/truecharts/ariang
  pullPolicy: IfNotPresent
  tag: 1.3.2@sha256:a50d73c166c8d44ea95a8a09daf4f35992ec78bfd80cd99099217410cdba9d28

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 8080
        port: 10276

portal:
  enabled: true
