image:
  repository: tccr.io/truecharts/owncast
  tag: 0.0.13@sha256:feb20e3da4720cc2f17af4a463763fbbdad134d35e2e2394bee560bf478e3dc6
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10088
        targetPort: 8080
  rtmp:
    enabled: true
    # externalTrafficPolicy: Local
    ports:
      rtmp:
        enabled: true
        port: 1935
        targetPort: 1935

persistence:
  config:
    enabled: true
    mountPath: "/app/data"

portal:
  enabled: true
