image:
  repository: tccr.io/truecharts/serpbear
  pullPolicy: IfNotPresent
  tag: latest@sha256:2ca013b79449797e055b210ddcdaade60211951760a65ecd654d64c88c68c96b

serpbear:
  user: admin
  password: secret
  session_duration: 24
  api_key: ""
  app_url: http://localhost:10605

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-env-secret'

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 3000
        port: 10605

persistence:
  data:
    enabled: true
    mountPath: /app/data

portal:
  enabled: true
