image:
  repository: tccr.io/truecharts/minetest
  pullPolicy: IfNotPresent
  tag: 5.6.1@sha256:ccd2b6736131d54a6903a8d0f25b998923865a4b344bb734d231d13e57744c49

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: UDP
        targetPort: 30000
        port: 30000

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config/.minetest"
  varrun:
    enabled: true

portal:
  enabled: true
