image:
  repository: tccr.io/truecharts/plex
  pullPolicy: IfNotPresent
  tag: 1.30.0.6486@sha256:c5f3f51c22c122882b8876cad4882d37e5c49e6635cac8994e22a40b1d894153

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"

plex:
  # User Defined
  serverIP: "127.0.0.1"
  additionalAdvertiseURL: ""
  disableGDM: true

env:
  PLEX_PREFERENCE_GDM: 'GdmEnabled={{ ternary "0" "1" .Values.plex.disableGDM }}'
  # User Defined
  ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
  PLEX_CLAIM: ""

portal:
  enabled: true
