image:
  repository: tccr.io/truecharts/deemix
  pullPolicy: IfNotPresent
  tag: latest@sha256:1c3215f779d1071f6d93bb86fb929e7570c634cbcca5554c65088ff4d133daf4

env:
  INTPORT: "{{ .Values.service.main.ports.main.targetPort }}"
  # User Defined
  DEEMIX_SINGLE_USER: false

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    enabled: true
    ports:
      main:
        port: 6595
        targetPort: 6595

persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/downloads"

portal:
  enabled: true
