image:
  repository: tccr.io/truecharts/endlessh
  pullPolicy: IfNotPresent
  tag: v2021.11.21@sha256:0ae05ee37bfbb92df870ef7b85ec56d04b99f22d3e924695cbd61e9cb0169050

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 2222
        port: 10128

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
