image:
  repository: tccr.io/truecharts/foldingathome
  pullPolicy: IfNotPresent
  tag: v7.6.21@sha256:cd15c9e877d922e56a5a0cfb01bc4bac652de33b7bb16de9beadedfe5afd2a1e

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 7396
        port: 7396
  control:
    enabled: true
    ports:
      control:
        enabled: true
        targetPort: 36330
        port: 36330

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
