image:
  repository: tccr.io/truecharts/protonmail-bridge
  tag: 2.4.8@sha256:30b174f32cd3933f762078c52c24ea138b7ee3399cbc25d49e281a45fd20cde7
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
  smtp:
    enabled: true
    ports:
      smtp:
        enabled: true
        port: 25
        targetPort: 25
  imap:
    enabled: true
    ports:
      imap:
        enabled: true
        port: 143
        targetPort: 143

persistence:
  config:
    enabled: true
    mountPath: "/root"

portal:
  enabled: false
