image:
  repository: tccr.io/truecharts/wikijs
  tag: 2.5.295@sha256:448e9f3a3464205fec867a099b5064c3ed8e9aeb0197b3726037b477ee7c7600
  pullPolicy: IfNotPresent

env:
  DB_TYPE: "postgres"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_PORT: "5432"
  DB_PASS:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

probes:
  liveness:
    path: "/healthz"
  readiness:
    path: "/healthz"
  startup:
    path: "/healthz"

service:
  main:
    ports:
      main:
        port: 10045
        targetPort: 3000

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: wikijs
  postgresqlDatabase: wikijs

# /wiki/data is a temporary dir. Without mounting as emptyDir it's only writable by root.
# https://docs.requarks.io/en/install/config#data-paths
persistence:
  wikicache:
    enabled: true
    mountPath: "/wiki/data/"
    type: emptyDir

portal:
  enabled: true
