image:
  repository: tccr.io/truecharts/appdaemon
  pullPolicy: IfNotPresent
  tag: v4.2.1@sha256:e9c2639389084bd3ea7b272d5239cf6da7b5e3eb49069bbcafd002e551681dda

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  TOKEN: "REPLACETHIS"

env:
  DASH_URL: "http://$HOSTNAME:5050"
  HA_URL: ""
  LATITUDE: 46
  LONGITUDE: -94
  ELEVATION: 1217
  TIMEZONE: "{{ .Values.TZ }}"

service:
  main:
    ports:
      main:
        port: 5050
        targetPort: 5050

persistence:
  conf:
    enabled: true
    mountPath: "/conf"
  varrun:
    enabled: true

portal:
  enabled: true
