image:
  repository: tccr.io/truecharts/homelablabelmaker
  tag: latest@sha256:a1e41adaafade429f7603b32f603bc809b0bd3ee4433ac382fd803ef979dce73
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

service:
  main:
    ports:
      main:
        port: 10581
        protocol: HTTP
        targetPort: 80

portal:
  enabled: true
