image:
  pullPolicy: IfNotPresent
  repository: splunk/splunk
  tag: 9.0.3@sha256:fac6a28e63551cea2cb423ae9670d8ce8d043a6d1f00b842331310f6e9a21df7

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

splunk:
  acceptLicense: true
  password: changeme
  extraArgs: []

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-splunk-config'

service:
  dataingest:
    enabled: true
    ports:
      dataingest:
        enabled: true
        port: 9997
        protocol: HTTP
        targetPort: 9997
  main:
    ports:
      main:
        port: 8000
        protocol: HTTP
        targetPort: 8000
  management:
    enabled: true
    ports:
      management:
        enabled: true
        port: 8089
        protocol: HTTP
        targetPort: 8089

persistence:
  appcreds:
    enabled: true
    mountPath: /opt/splunk/etc/
  config:
    enabled: true
    mountPath: /opt/splunk/var
  datap:
    enabled: true
    mountPath: /splunkdata

portal:
  enabled: true
